### ISSUE TITLE
Add a description for each user in the `who-to-follow` section.

### ISSUE THREAD

**Issue by pazguille** [pazguille/offline-first#20]
> In the `who-to-follow` section you list some Twitter usernames. Why should I follow them? What relevant do they do? That should be answered as a description for each user.

**Comment by ichpuchtli** [comment]
- tofumatt (Matthew Riley) - Works at mozilla, creator of localForage (localstroage, IndexedDb and WebSQL Wrapper)
 - Jake Archibald - Self described service worker fanatic, works at google helping make offline web apps a thing

Christian's and john's twitter have a low signal to noise ratio. I wouldn't demand people follow these guys.

**Comment by pazguille** [comment]
Updated. Thank you!
