### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ReadmeCritic** [pazguille/offline-first#33]
this link does not work anymore
- https://unoyunodiez.com/2015/09/07/modern-mobile-web-development-breaking-the-rules-beating-delays-improving-responsiveness-and-performance-ii/  at line 313

this link is timing out at the moment
- https://blog.getchop.io/designing-for-accidental-disconnects-our-first-attempt-at-an-offline-approach-2ac0bdb6d170#.i8odfrxxs at line 61

**Comment by pazguille** [comment]
Fixed.
